title: Harnessing Artificial Intelligence for Optimized Pediatric Tumor Evaluation (HOPE)
logo: /assets/img/CN_Vrt_RGB_HiRes_Lg.png
description: Platform Overview
show_downloads: false
google_analytics:
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
